# Generated by Django 3.2.6 on 2021-10-30 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('thread', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sub_thread',
            name='replyto',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='thread.thread'),
            preserve_default=False,
        ),
    ]
