# Generated by Django 3.2.6 on 2021-11-07 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('thread', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sub_thread',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='sub_thread',
            name='replyto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thread.thread'),
        ),
    ]
