# Generated by Django 3.2.6 on 2021-10-22 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dormitory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dormitory',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='dormitorys'),
        ),
        migrations.AddField(
            model_name='dormitory',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
