# Generated by Django 3.2.6 on 2021-11-07 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dormitory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dormitory',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='review',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='review',
            name='reviewto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dormitory.dormitory'),
        ),
    ]
