# Generated by Django 3.2.6 on 2021-10-22 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dormitory', '0002_auto_20211022_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dormitory',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='static/dormitorys/icon'),
        ),
        migrations.AlterField(
            model_name='dormitory',
            name='seen',
            field=models.IntegerField(default=0),
        ),
    ]
