# Generated by Django 3.2.6 on 2021-10-30 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dormitory', '0003_auto_20211023_0124'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='report',
            field=models.IntegerField(default=0),
        ),
    ]
