# Generated by Django 3.2.6 on 2021-10-30 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dormitory', '0004_review_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='reviewto',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='dormitory.dormitory'),
            preserve_default=False,
        ),
    ]
